from pathlib import Path

import jupytext
import pytest

from implectus.util import (
    implectus_header_cell,
    is_autogenerated,
    is_implectus_header_cell,
)

from .util import create_nb


def test_implectus_header_cell():
    cell = implectus_header_cell("file.py")
    assert is_implectus_header_cell(cell)


@pytest.mark.parametrize("filename", ("file.py", "file.ipynb", "file.md"))
def test_is_autogenerated_true(tmpdir_cd, filename):
    nb = create_nb(cells=[implectus_header_cell("file.py")])
    jupytext.write(nb, filename)
    assert is_autogenerated(filename)


@pytest.mark.parametrize("filename", ("file.py", "file.ipynb", "file.md"))
def test_is_autogenerated_false(tmpdir_cd, filename):
    Path(filename).write_text("Manually generated")
    assert not is_autogenerated(filename)


def test_is_autogenerated_missing():
    assert not is_autogenerated("file_that_doesn't_exist")
